# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"


gem "spicy-proton", "~> 2.1"

gem "faker", "~> 2.19"
